fix: fixes sonar refuses to start if ethernet device is not present
Fixes Error mentioned in https://github.com/mainsail-crew/sonar/issues/3

Also fixes error ERR Trap is not triggered due missing set -Ee

Signed-off-by: Stephan Wendel <me@stephanwe.de>

diff --git a/sonar b/sonar
--- a/sonar
+++ b/sonar
@@ -10,6 +10,9 @@
 
 # shellcheck enable=require-variable-braces
 
+# Exit on Errors
+set -Ee
+
 # Make sure script runs with root priviledges
 if [ "$(id -u)" != "0" ]; then
     echo -e "\nSonar - A WiFi Keepalive daemon\n"
